name: Deploy EKS CDK Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js (for CDK CLI, if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean install Python dependencies
        run: |
          rm -rf .venv
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip uninstall -y aws-cdk.aws-eks aws-cdk.core || true
          pip install aws-cdk-lib==2.200.1 constructs==10.3.0 cdk-cli

      - name: Verify CDK package source and version
        run: |
          source .venv/bin/activate
          python -c "import aws_cdk; print('CDK:', aws_cdk.__version__)"
          python -c "from aws_cdk import aws_eks as eks; import inspect; print('eks.Cluster:', inspect.getfile(eks.Cluster))"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: CDK Bootstrap
        run: |
          source .venv/bin/activate
          cdk bootstrap

      - name: Deploy CDK Stack
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never
